// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace BlokAI
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"game_id")]
            public float Game_id { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"sezona")]
            public string Sezona { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"datum")]
            public string Datum { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"protivnik")]
            public string Protivnik { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"je_domacin")]
            public float Je_domacin { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"forma_5")]
            public float Forma_5 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"forma_10")]
            public float Forma_10 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"forma_opp_5")]
            public float Forma_opp_5 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"forma_opp_10")]
            public float Forma_opp_10 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"label")]
            public float Label { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"game_id")]
            public float Game_id { get; set; }

            [ColumnName(@"sezona")]
            public float[] Sezona { get; set; }

            [ColumnName(@"datum")]
            public float[] Datum { get; set; }

            [ColumnName(@"protivnik")]
            public float[] Protivnik { get; set; }

            [ColumnName(@"je_domacin")]
            public float Je_domacin { get; set; }

            [ColumnName(@"forma_5")]
            public float Forma_5 { get; set; }

            [ColumnName(@"forma_10")]
            public float Forma_10 { get; set; }

            [ColumnName(@"forma_opp_5")]
            public float Forma_opp_5 { get; set; }

            [ColumnName(@"forma_opp_10")]
            public float Forma_opp_10 { get; set; }

            [ColumnName(@"label")]
            public float Label { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
